os: linux
language: c++
compiler: gcc
before_script:
    - hg clone https://bitbucket.org/eigen/eigen
    - cd eigen
    - mkdir build
    - cd build
    - cmake ..
    - make
before_install: 
    - sudo apt-get update
    - sudo apt-get install -y liblapacke-dev liblapack-dev
script: make
