os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
        env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
language: c++
compiler: g++
before_install: 
    - sudo apt-get update
    - sudo apt-get install -y liblapack-dev
    - eval "${MATRIX_EVAL}"
script: ls && cd eigen && mkdir build && cd build && cmake .. && make && cd ../.. && mkdir build && cd build && cmake .. && make
