os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
        env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
language: c++
compiler: g++
before_install: 
    - sudo apt-get update
    - sudo apt-get install -y liblapacke-dev liblapack-dev libeigen3-dev
    - eval "${MATRIX_EVAL}"
script: make
